### ISSUE TITLE
Module doesn't load/show

### ISSUE THREAD

**Issue by importantlyearnest** [daterrell/MMM-CountDown#4]
Thanks for making this. Are you able to share an example of the config? I think I'm missing something as I've filled out all the parameters but the countdown is not showing up.

My config is pasted below:
		{
			module: 'MMM-CountDown',
			position: 'top_left',
			config: {
				event: "Mom's Birthday!",
				date: 2024-10-14,
				isAnnual: true,
				annualDaysDiff: 14,
			}
		},

**Comment by daterrell** [comment]
Hey, I sure do!  Use it all the time on our MM, here's an example below.  I'd suggest making sure  you have `daysLabel` and `timezone`, as well as enclosing the date in quotes and see if that works.  LMK
 
```
{
      module: "MMM-CountDown",
      position: "bottom_left",
      config: {
        timezone: "America/Los_Angeles",
        event: "Halloween:",
        date: "2021-10-31",
        daysLabel: "days ",
        isAnnual: true,
      }
    },
```
